Repository stolostron/hypershift-deployment-controller, pull requests merged in 2022-04, with the labels that each got.

#61 trigger image build on CI
  README.md
Labels: approved, lgtm

#62 Origin/default manifest
  pkg/controllers/aws_infra.go
  pkg/controllers/aws_infra_test.go
  pkg/controllers/azure_infra.go
  pkg/controllers/hypershiftdeployment_controller.go
  pkg/controllers/hypershiftdeployment_controller_test.go
Labels: enhancement, approved, lgtm

#63 Set default values for hosted cluster
  pkg/controllers/default_resources.go
  pkg/controllers/hypershiftdeployment_controller.go
Labels: approved, lgtm

#64 Make ManifestWork the default, remove the override for Manifestwork, and remove the code that creates local resources.
  pkg/controllers/default_resources.go
Labels: approved, lgtm

#66 Quickstart
  docs/content.md
  docs/hostedcontrolplanecluster-flow.jpg
  samples/quickstart/README.md
  samples/quickstart/start.sh
Labels: approved, lgtm

#65 Keep hc and np in hostingCluster for Orphan override option
  api/v1alpha1/hypershiftdeployment_types.go
  config/crd/cluster.open-cluster-management.io_hypershiftdeployments.yaml
  docs/provision_hypershift_clusters_by_mce.md
  pkg/controllers/hypershiftdeployment_controller.go
  pkg/controllers/hypershiftdeployment_controller_test.go
  pkg/controllers/manifestwork.go
  pkg/controllers/manifestwork_test.go
  samples/hypershift-deployment-to-manifestwork.yaml
Labels: approved, lgtm

#68 Remove oidc service def. Not required
  pkg/controllers/default_resources.go
Labels: approved, lgtm

#70 Add vendor and cloud label for managed cluster
  pkg/controllers/autoimport/autoimport_controller.go
  pkg/controllers/autoimport/autoimport_controller_test.go
Labels: approved, lgtm

#69 delete the hosted cluster after the managed cluster is deleted
  pkg/constant/constants.go
  pkg/controllers/autoimport/autoimport_controller.go
  pkg/controllers/autoimport/autoimport_controller_test.go
  pkg/controllers/hypershiftdeployment_controller.go
Labels: approved, lgtm

#72 Add scripts to test sd case
  Makefile
  samples/quickstart/create-aws-hosted-cluster.sh
  samples/quickstart/create-policy.sh
  samples/quickstart/start.sh
Labels: approved, lgtm

#71 Set delete option foreground when need to delete namespace
  pkg/controllers/manifestwork.go
Labels: approved, lgtm

#74 Vendorize with final branch for ACM2.5, OCP 4.10, using hypershift:re…
  config/crd/cluster.open-cluster-management.io_hypershiftdeployments.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#73 Update owners
  OWNERS
Labels: approved, lgtm

#75 Additionaltrustbundles
  pkg/controllers/configuration.go
  pkg/controllers/manifestwork_test.go
Labels: approved, lgtm

#77 Update print column conditions:
  api/v1alpha1/hypershiftdeployment_types.go
  config/crd/cluster.open-cluster-management.io_hypershiftdeployments.yaml
  pkg/controllers/manifestwork.go
  pkg/controllers/manifestwork_test.go
Labels: bug, approved, lgtm

#78 Add support for Spec.ServiceAccountSigningKey
  config/crd/cluster.open-cluster-management.io_hypershiftdeployments.yaml
  go.mod
  go.sum
  pkg/controllers/configuration.go
  pkg/controllers/manifestwork_test.go
Labels: approved, lgtm

#76 Add integration tests
  Makefile
  go.mod
  go.sum
  pkg/constant/constants.go
  pkg/controllers/aws_infra.go
  pkg/controllers/azure_infra.go
  pkg/controllers/default_resources.go
  pkg/controllers/hypershiftdeployment_controller.go
  pkg/controllers/infra_interface.go
  pkg/controllers/manifestwork.go
  pkg/main.go
  test/integration/externalcrds/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  test/integration/externalcrds/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
  test/integration/integration_suite_test.go
  test/integration/manifest_test.go
Labels: approved, lgtm

#80 Add infra-id label to HypershiftDeployment and update constants
  pkg/constant/constants.go
  pkg/controllers/aws_infra.go
  pkg/controllers/aws_infra_test.go
  pkg/controllers/azure_infra.go
  pkg/controllers/default_resources.go
  pkg/controllers/hypershiftdeployment_controller.go
  pkg/controllers/hypershiftdeployment_controller_test.go
  pkg/controllers/manifestwork.go
  pkg/controllers/manifestwork_test.go
  pkg/helper/helpers.go
  samples/quickstart/README.md
Labels: approved, lgtm

#79 Generate etcd encryption secret for Configure=T path
  pkg/controllers/configuration.go
  pkg/controllers/configuration_test.go
  pkg/controllers/default_resources.go
  pkg/controllers/manifestwork.go
  pkg/controllers/manifestwork_test.go
  test/integration/manifest_test.go
Labels: approved, lgtm

#81 Set reason for condition IAMConfigured to NA
  api/v1alpha1/hypershiftdeployment_types.go
  pkg/controllers/hypershiftdeployment_controller.go
  pkg/controllers/infra_interface.go
  pkg/controllers/manifestwork.go
  test/integration/manifest_test.go
Labels: approved, lgtm

#84 Do not create HC configuration items in hosting cluster
  pkg/controllers/configuration.go
  pkg/controllers/manifestwork_test.go
Labels: approved, lgtm

#85 Aws & Azure infrastructure mock tests
  go.mod
  pkg/controllers/aws_infra.go
  pkg/controllers/aws_infra_test.go
  pkg/controllers/azure_infra.go
  pkg/controllers/azure_infra_test.go
  pkg/controllers/hypershiftdeployment_controller_test.go
  pkg/controllers/infra_interface.go
  pkg/controllers/manifestwork.go
Labels: approved, lgtm

#87 Update hypershift main
  config/crd/cluster.open-cluster-management.io_hypershiftdeployments.yaml
  go.mod
  go.sum
Labels: approved, lgtm
